### ISSUE TITLE
set up health

### ISSUE THREAD

**Issue by DiTo97** [SS-research/omniwear#10]
## TODOs

- [x] script printing with permissions
- [x] Read health data as stream with health features, reading interval and frequency defined in health_data_page.dart
- [x] module with retrieval of collection config

## resources

- https://pub.dev/packages/health
