### ISSUE TITLE
Global config.yaml file

### ISSUE THREAD

**Issue by giuseppeambrosio97** [SS-research/omniwear#13]
## TODOs

- [x] add a global config.yaml for health data and inertial data
- [x] configure the health module to use the config from config.yaml file as default value
- [x] configure the inertial module to use the config from config.yaml file as default value
