### ISSUE TITLE
Define SQLite models

### ISSUE THREAD

**Issue by giuseppeambrosio97** [SS-research/omniwear#14]
## TODOs

- [x] Device info models
- [x] Health models
- [x] Inertial models
- [x] Session collection models
- [x] Config collection models

## References

- https://docs.powersync.com/client-sdk-references/flutter
- sqlite connector with only raw sql: https://pub.dev/packages/sqflite
- flutter ORM based on sqflite: https://pub.dev/packages/sqfentity
- https://prisma.pub/
