### ISSUE TITLE
set up inertial

### ISSUE THREAD

**Issue by DiTo97** [SS-research/omniwear#2]
## TODOs

- [x] script printing inertial events with permissions
- [x] and magnetometer
- [x] configuring streams collection
- [x] module with retrieval of collection config
- [x] synchronizing events streams
- [ ] add barometer

## notes

- UserAccelerometerEvent should be used for accelerometer as it is gravity-corrected

## resources

- https://pub.dev/packages/sensors_plus
- [zips one element at the time from each stream, blocking](https://pub.dev/documentation/rxdart/latest/rx/ZipStream-class.html)
- [merges elements from any stream in chronological order, non-blocking](https://pub.dev/documentation/rxdart/latest/rx/MergeStream-class.html)
- [zips the last element from each stream until replacement, blocking](https://pub.dev/documentation/rxdart/latest/rx/CombineLatestStream-class.html)
- [composite subscription clearing all underlying streams at once](https://pub.dev/documentation/rxdart/latest/rx/CompositeSubscription-class.html)
