### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by giuseppeambrosio97** [SS-research/omniwear#20]
- [ ] #46
- [ ] Refactor the repository to have omniwear package and omniwear flutter app (with widget, etc).
- [x] Implements remote DB (understand if a backend is needed).
- [ ] Github actions to release on Apple and Android store
