### ISSUE TITLE
mvp/batch-storage-writer

### ISSUE THREAD

**Issue by giuseppeambrosio97** [SS-research/omniwear#34]
Batch data locally for inertial collection duration and then send in one transaction either to local SQLite or to remote server.

Send the message to the api (if remote collection) or write on sqtlite (if local collection) and the end of:

- [x] health reading frequency for health data @DiTo97 so here there is nothing to do, because we already send data in batch
- [x] inertial collection duration, here we have to implement a buffer mechanism to collect data and then send (remote) or write (locally) at the end of the collection duration period.
- [x] @DiTo97 figure out whether you need to define a more defined data batching process, such as collect until you reach n datapoints and then send them to block, or time-based: collect for n seconds and then send to block.

## Todos:

- [x] create post bulk for ts-health and ts-inertial
- [x] change in data create bulk dto
- [x] Data Transport 
- [x] WebTransport
- [x] HttpBatchTransport
