### ISSUE TITLE
wearables engine

### ISSUE THREAD

**Issue by giuseppeambrosio97** [SS-research/omniwear#46]
# TODOs

The wearables engine should be native and connect via UDP for both [Android ](https://github.com/wearable-motion-capture/sensor-stream-apps/) and [iOS](https://github.com/SPICExLAB/SensorTracker).

- [ ] setup base wear app
- [ ] collect data on wear app
- [ ] enable communication and sync between smartphone and smartwatch app
- [ ] read device info from watch when a new participant registers
- [ ] connect to ip url from the smartphone app.
- [ ] once smartphone connected list possible datasets in watch app
- [ ] start streaming in both smartphone and smartwatch
