### ISSUE TITLE
set up device info

### ISSUE THREAD

**Issue by DiTo97** [SS-research/omniwear#7]
## TODOs

- [x] script printing device info for both android and iOS
- [x] normalizing device info in a unified way (iOS product name)
- [x] module with automatic platform detection returning device info (granted permissions)

## resources

- https://pub.dev/packages/device_info_plus
- https://github.com/kyle-seongwoo-jun/flutter_apple_product_name
- https://gist.github.com/adamawolf/3048717
